### ISSUE TITLE
Smoothness and feasibility loss different from paper?

### ISSUE THREAD

**Issue by wangzizhao** [ZJU-FAST-Lab/ego-planner#15]
1. smoothness loss
From this [line](https://github.com/ZJU-FAST-Lab/ego-planner/blob/master/src/planner/bspline_opt/src/bspline_optimizer.cpp#L419), it seems smoothness loss only uses jerk.
2. feasibility loss
In this [line](https://github.com/ZJU-FAST-Lab/ego-planner/blob/master/src/planner/bspline_opt/src/bspline_optimizer.cpp#L458) the feasibility loss doesn't use the SECOND_DERIVATIVE_CONTINOUS loss in the paper, also it doesn't consider jerk.

Are the above two points some modifications based on empirical results?

**Comment by bigsuperZZZX** [comment]
That's true, these are empirical modifications from the paper.

1. The reason why we only use jerk is that it seems no significant differences in smoothness performance compared to combining acceleration and jerk, while using only the jerk can save a little computation.
2. The reason is the same above.

Also, it's encouraged to test the performance by the user themselves, so we use some flags to help them easily toggle on-off the functions easily.
