### ISSUE TITLE
Improper camere-IMU time synchronization on Realsense D435i with the driver modifications

### ISSUE THREAD

**Issue by Pallav1299** [ZJU-FAST-Lab/ego-planner#25]
I tried using the modified realsense-ros driver to get input for Stereo-inertial SLAM using VINS-Fusion. 

Although the projector dots were almost removed, I witnessed that the changes affected the IMU and camera timestamps. 
- How can this affect the SLAM performance?
- How should we ideally use it for Stereo-inertial SLAM configuration?
- I also noticed that on using the modified version of realsense-ros driver with VINS-fusion promped "wait for imu ..." several times. Does it  mean that the changes affected the time synchronization between camera and IMU?

I compiled the realsense-ros wrapper against the latest librealsense sdk since I was getting runtime errors while building with the suggested librealsense-2.30.0 version. 

Open to suggestions.

**Comment by bigsuperZZZX** [comment]
I think this function will not affect the SLAM performance since we have been using it for a long time.
You can adjust the frame rate in launch files so that the camera outputs at the same rate as not using such a feature.
One minor difference is the time stamps between depth and gray-scale images since they are outputted alternatively.
But this difference should not affect the mapping performance since the time deviation is very small (~16ms at 30fps setting).

**Comment by bigsuperZZZX** [comment]
It no more questions, I will close this issue.

**Comment by Pallav1299** [comment]
@bigsuperZZZX, Thanks for the clarification.

**Comment by Pallav1299** [comment]
I noticed a difference in IMU and Camera timestamps. Please check the attached images for the same. I've faced this issue earlier as well. Setting the "initial_reset" flag to "true" acted as a workaround. But not this time. 

This issue leads to degradation in SLAM preformance in VINS.

**Camera timestamp:**
![camera_timestamp](https://user-images.githubusercontent.com/32015105/136010817-75f357a6-6109-4cf4-ac08-c869ebd9197a.png)

**IMU timestamp:**
![imu_timestamp](https://user-images.githubusercontent.com/32015105/136010823-ae656ea1-7b3c-43b5-bf97-d5d16b76f91d.png)
